name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://noru-kang.github.io/feed.xml"
          max_post_count: 5
          disable_html_encoding: true # ( ) 등이 깨지지 않게 설정
          template: "| $title | [바로가기]($url) |$newline" # 반드시 $newline을 끝에 붙여야 행이 나뉩니다.
